/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class Dokter extends javax.swing.JFrame {

    /**
     * Creates new form Dokter
     */
    public Dokter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtxtnama = new javax.swing.JTextField();
        jtxtalamat = new javax.swing.JTextField();
        jtxtusia = new javax.swing.JTextField();
        jtxtjenis = new javax.swing.JTextField();
        jtxtgol = new javax.swing.JTextField();
        jtxtstatus = new javax.swing.JTextField();
        jtxtkewar = new javax.swing.JTextField();
        jtxtwaktu = new javax.swing.JTextField();
        jtxtspesial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbdokter = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Identitas"));
        jPanel2.setToolTipText("");
        jPanel2.setName(""); // NOI18N
        jPanel2.setLayout(null);

        jLabel3.setText("Dokter Spesialis");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 270, 120, 14);

        jtxtnama.setEnabled(false);
        jtxtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnamaActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtnama);
        jtxtnama.setBounds(150, 20, 240, 30);

        jtxtalamat.setEnabled(false);
        jPanel2.add(jtxtalamat);
        jtxtalamat.setBounds(150, 50, 240, 30);

        jtxtusia.setEnabled(false);
        jtxtusia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtusiaActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtusia);
        jtxtusia.setBounds(150, 80, 240, 30);

        jtxtjenis.setEnabled(false);
        jPanel2.add(jtxtjenis);
        jtxtjenis.setBounds(150, 110, 240, 30);

        jtxtgol.setEnabled(false);
        jPanel2.add(jtxtgol);
        jtxtgol.setBounds(150, 140, 240, 30);

        jtxtstatus.setEnabled(false);
        jtxtstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtstatusActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtstatus);
        jtxtstatus.setBounds(150, 170, 240, 30);

        jtxtkewar.setEnabled(false);
        jPanel2.add(jtxtkewar);
        jtxtkewar.setBounds(150, 200, 240, 30);

        jtxtwaktu.setEnabled(false);
        jtxtwaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtwaktuActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtwaktu);
        jtxtwaktu.setBounds(150, 230, 240, 30);

        jtxtspesial.setForeground(new java.awt.Color(255, 255, 255));
        jtxtspesial.setEnabled(false);
        jPanel2.add(jtxtspesial);
        jtxtspesial.setBounds(150, 260, 240, 30);

        jLabel4.setText("Nama");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 30, 120, 14);

        jLabel5.setText("Alamat");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 60, 120, 14);

        jLabel6.setText("Usia");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 90, 120, 14);

        jLabel7.setText("Jenis Kelamin");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 120, 120, 14);

        jLabel8.setText("Gol Darah");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 150, 120, 14);

        jLabel9.setText("Status");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 180, 120, 14);

        jLabel10.setText("Kewarganegaraan");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 210, 120, 14);

        jLabel11.setText("Waktu Praktik");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 240, 120, 14);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(25, 111, 400, 340);

        jLabel1.setText("Pemilihan Dokter");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(158, 11, 115, 33);

        jLabel2.setText("Pilih Dokter");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(41, 63, 75, 37);

        jcbdokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Salah Satu --", "dr. Darren", "dr. Jesse", "dr. Henry Lau" }));
        jcbdokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbdokterActionPerformed(evt);
            }
        });
        getContentPane().add(jcbdokter);
        jcbdokter.setBounds(130, 70, 180, 20);

        setBounds(0, 0, 516, 546);
    }// </editor-fold>//GEN-END:initComponents

    private void jcbdokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbdokterActionPerformed
        // TODO add your handling code here:
        if (jcbdokter.getSelectedItem().equals("dr. Darren")) {
            jtxtnama.setText("dr. Matthew Darren");
            jtxtalamat.setText("Hermione Rd, 17");
            jtxtusia.setText("28 tahun");
            jtxtjenis.setText("Laki-Laki");
            jtxtgol.setText("O");
            jtxtstatus.setText("Belum Menikah ");
            jtxtkewar.setText("Filipina");
            jtxtspesial.setText("Dokter Spesialis Bedah Syaraf");
            jtxtwaktu.setText(" Pagi (07.00-15.00)");
        }
        else if(jcbdokter.getSelectedItem().equals("dr. Jesse")){
            jtxtnama.setText("dr. Jessica Mariana");
            jtxtalamat.setText("Vold Rd, 119");
            jtxtusia.setText("30 Tahun");
            jtxtjenis.setText("Perempuan");
            jtxtgol.setText("AB");
            jtxtstatus.setText("Menikah");
            jtxtkewar.setText("Indonesia");
            jtxtspesial.setText("Dokter Spesialis Organ Dalam");
            jtxtwaktu.setText(" Sore (16.00-21.00)");
        }
        else if(jcbdokter.getSelectedItem().equals("dr. Henry Lau")){
            jtxtnama.setText("dr. Henry Lau");
            jtxtalamat.setText("Slytherin Rd, 39");
            jtxtusia.setText("26 Tahun");
            jtxtjenis.setText("Laki-Laki");
            jtxtgol.setText("B");
            jtxtstatus.setText("Belum Menikah");
            jtxtkewar.setText("China");
            jtxtspesial.setText("Dokter Spesialis Mata");
            jtxtwaktu.setText(" Malam (21.00-06.00)");
        }
    }//GEN-LAST:event_jcbdokterActionPerformed

    private void jtxtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnamaActionPerformed

    private void jtxtstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtstatusActionPerformed

    private void jtxtwaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtwaktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtwaktuActionPerformed

    private void jtxtusiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtusiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtusiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jcbdokter;
    private javax.swing.JTextField jtxtalamat;
    private javax.swing.JTextField jtxtgol;
    private javax.swing.JTextField jtxtjenis;
    private javax.swing.JTextField jtxtkewar;
    private javax.swing.JTextField jtxtnama;
    private javax.swing.JTextField jtxtspesial;
    private javax.swing.JTextField jtxtstatus;
    private javax.swing.JTextField jtxtusia;
    private javax.swing.JTextField jtxtwaktu;
    // End of variables declaration//GEN-END:variables
}
